# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#export HOST_DEFAULT_IP="10.2.238.117"
#export LIBVIRT_DEFAULT_URI="qemu+ssh://root@10.2.238.117/system"
