version: '3.8'
x-node:
  &default-node
  build: ./node
  env_file: ./secret/node.env
  privileged: true
  networks:
    - shit

services:
  control:
    container_name: shit-control
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - 8080:8080
    networks:
      - shit
#  n1:
#    << : *default-node
#    container_name: chaos-n1
#    hostname: n1
#  n2:
#    << : *default-node
#    container_name: chaos-n2
#    hostname: n2
#  n3:
#    << : *default-node
#    container_name: chaos-n3
#    hostname: n3
#  n4:
#    << : *default-node
#    container_name: chaos-n4
#    hostname: n4
#  n5:
#    << : *default-node
#    container_name: chaos-n5
#    hostname: n5

networks:
  shit:
